### ISSUE TITLE
Tracking issue for make-a-fortune v3

### ISSUE THREAD

**Issue by skyzh** [skyzh/make-a-fortune#80]
So we are officially into the progress of being a web client of https://treehole.space. To support this, we might need to:

- [ ] Adapt to new API
- [ ] Redesign homepage, reply, etc.
- [ ] Add new features that treehole.space support
- [ ] Become an official client of treehole.space
